깃허브 자신의 계정에 수업과 숙제를 올린 소스코드만 참조가능
(그 외의 참조는 부정으로 간주 F처리)

데이터 로드
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data' columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'] data = pd.read_csv(url, names=columns)

데이터 확인
print(data.head())

해당 소스를 이용하여 ML 분류 RF, LR, DT

해당 소스를 이용하여 FCNN

해당 소스를 이용하여 CNN

모든 소스에는 F1값 및 confusion matrix 표시

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data' 
columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'] 
df = pd.read_csv(url, names=columns)

In [4]:
df

buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [5]:

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['buying'] = label_encoder.fit_transform(df['buying'])
df['buying'].value_counts().sort_index()

df['maint'] = label_encoder.fit_transform(df['maint'])
df['maint'].value_counts().sort_index()

df['doors'] = label_encoder.fit_transform(df['doors'])
df['doors'].value_counts().sort_index()

df['persons'] = label_encoder.fit_transform(df['persons'])
df['persons'].value_counts().sort_index()

df['lug_boot'] = label_encoder.fit_transform(df['lug_boot'])
df['lug_boot'].value_counts().sort_index()

df['safety'] = label_encoder.fit_transform(df['safety'])
df['safety'].value_counts().sort_index()

df['class'] = label_encoder.fit_transform(df['class'])
df['class'].value_counts().sort_index()

class
0     384
1      69
2    1210
3      65
Name: count, dtype: int64

In [6]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [7]:
df = df.dropna()
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [8]:
X=df.drop('class',axis=1)
X.head()

buying  maint  doors  persons  lug_boot  safety
0       3      3      0        0         2       1
1       3      3      0        0         2       2
2       3      3      0        0         2       0
3       3      3      0        0         1       1
4       3      3      0        0         1       2

In [9]:
y = df['class']
y.value_counts()

class
2    1210
0     384
1      69
3      65
Name: count, dtype: int64

In [10]:
y = pd.get_dummies(y).values
y

array([[False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       ...,
       [False, False,  True, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [11]:
X = X.values
X

array([[3, 3, 0, 0, 2, 1],
       [3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       ...,
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]])

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0) 

# 입력, 출력 차원 분석

In [17]:
n_features, n_outputs = X_train.shape[1], y_train.shape[1]
print(n_features, n_outputs)

6 4


In [19]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam

model = Sequential() 

model.add(Dense(10, input_shape= (n_features,), activation='tanh'))
model.add(Dense(8, activation='tanh'))
model.add(Dense(6, activation='tanh'))
model.add(Dense(n_outputs, activation='softmax'))

model.compile(Adam(), 'categorical_crossentropy', metrics=['accuracy']) # 정확도 지표 accuracy(분류) <=> mse(회귀) 

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 10)                  │              70 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 6)                   │              54 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 4)                   │              28 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 240 (960.00 B)

 Trainable params: 240 (960.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model_history=model.fit(x=X_train, y=y_train, epochs=30, batch_size=32,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)  #다중 분류 문제에서 원 - 핫 인코딩 => 숫자로 바꾸는 방법임 
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.0692 - loss: 1.6130 - val_accuracy: 0.4798 - val_loss: 1.2689
Epoch 2/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5875 - loss: 1.2161 - val_accuracy: 0.6908 - val_loss: 1.0414
Epoch 3/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7015 - loss: 1.0154 - val_accuracy: 0.6936 - val_loss: 0.9168
Epoch 4/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6837 - loss: 0.9242 - val_accuracy: 0.6936 - val_loss: 0.8575
Epoch 5/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6891 - loss: 0.8544 - val_accuracy: 0.6936 - val_loss: 0.8332
Epoch 6/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6992 - loss: 0.8199 - val_accuracy: 0.6965 - val_loss: 0.8210
Epoch 7/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7033 - loss: 0.7909 - val_accuracy: 0.7023 - val_loss: 0.8108
Epoch 8/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6905 - loss: 0.7968 - val_accuracy: 0.7052 - val_loss:

In [21]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix

# 이진 분류 모델의 성능 평가 
# precision(클래스별 정확도), recall,f1-score(재현율, 균형), support(샘플 개수) 
print(classification_report(y_test_class,y_pred_class))


print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.47      0.32      0.38        79
           1       0.00      0.00      0.00        17
           2       0.78      0.95      0.86       240
           3       1.00      0.10      0.18        10

    accuracy                           0.73       346
   macro avg       0.56      0.34      0.35       346
weighted avg       0.68      0.73      0.69       346

[[ 25   0  54   0]
 [  7   0  10   0]
 [ 12   0 228   0]
 [  9   0   0   1]]


C:\Users\tansy\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\tansy\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\tansy\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
